
export const API_BASEURL = `${process.env.NEXT_PUBLIC_API_URL}/api/v1`;
export const WSS_URL = process.env.NEXT_PUBLIC_WEB_SOCKET_URL;

export const routeTo = {
    login: "/",
    forgotPassword: "/auth/forgot-password",
    sentMagicLink: "/auth/sent-magic-link",
    createPassword: "/auth/create-password",
    createPasswordSuccess: "/auth/create-password-success",
    dashboard: "/app/dashboard",

    farms: "/app/farm-management/farms",
    farmers: "/app/farm-management/farmers",
    addLeadFarmer: "/app/farm-management/farmers/add-lead-farmer",
    editLeadFarmer: "/app/farm-management/farmers/edit-lead-farmer",
    viewLeadFarmer: "/app/farm-management/farmers/view-lead-farmer",
    addSmallholderFarmer: "/app/farm-management/farmers/add-smallholder-farmer",
    editSmallholderFarmer: "/app/farm-management/farmers/edit-smallholder-farmer",
    viewSmallholderFarmer: "/app/farm-management/farmers/view-smallholder-farmer",
    products: "/app/farm-management/products",

    warehouses: "/app/supply-chain-management/warehouses",
    viewWarehouse: "/app/supply-chain-management/warehouses/view-warehouse",
    inflowOrders: "/app/supply-chain-management/inflow-orders",
    inflowOrdersAdd: "/app/supply-chain-management/inflow-orders/add-inflow",
    inflowOrdersView: "/app/supply-chain-management/inflow-orders/view-inflow",
    inflowOrdersEdit: "/app/supply-chain-management/inflow-orders/edit-inflow",
    outflowOrders: "/app/supply-chain-management/outflow-orders",
    outflowOrdersAdd: "/app/supply-chain-management/outflow-orders/add-outflow",
    outflowOrdersView: "/app/supply-chain-management/outflow-orders/view-outflow",
    outflowOrdersEdit: "/app/supply-chain-management/outflow-orders/edit-outflow",
    customers: "/app/supply-chain-management/customers",
    viewCustomers: "/app/supply-chain-management/customers/view-customer",

    creditManagement: "/app/credit-management/credits",
    inputCreditManagement: "/app/credit-management/input-credits",
    inputCreditProcurement: "/app/credit-management/input-credit-procurement",
    
    inflowApprovals: "/app/approvals/inflow-orders",
    viewInflowApprovals: "/app/approvals/inflow-orders/view-inflow",
    outflowApprovals: "/app/approvals/outflow-orders",
    viewOutflowApprovals: "/app/approvals/outflow-orders/view-outflow",
    creditRequestApprovals: "/app/approvals/credit-request",
    viewCreditRequestApprovals: "/app/approvals/credit-management/view-request",
    creditWarehouseApprovals: "/app/approvals/warehouse-credit",
    farmerRegistrationRequests: "/app/approvals/farmer-registration-requests",
    viewFarmerRegistrationRequest: "/app/approvals/farmer-registration-requests",

    employeeManagement: "/app/employee-management",
    employeeProfiles: "/app/employee-management/profiles",
    employeeProfilesAdd: "/app/employee-management/profiles/add-employee",
    employeeProfilesEdit: "/app/employee-management/profiles/edit-employee",
    employeeProfilesView: "/app/employee-management/profiles/view-employee",
    employeeJobTitles: "/app/employee-management/job-titles",
    employeeViewJobTitle: "/app/employee-management/job-titles/view-job-title",
    employeeDepartments: "/app/employee-management/departments",
    employeeViewDepartment: "/app/employee-management/departments/view-department",

    leaveManagementLeaveRequests: "/app/leave-management/leave-requests",
    leaveManagementLeaveRequestTypes: "/app/leave-management/leave-request-types",
    training: "/app/training",
    trainingCreate: "/app/training/create",
    trainingView: "/app/training/view",
    trainingEdit: "/app/training/edit",

    accountingExpenses: "/app/accounting/expenses",
    accountingWaybills: "/app/accounting/waybills",
    accountingViewWaybill: "/app/accounting/waybills/view-waybill",
    accountingInvoices: "/app/accounting/invoices",
    accountingViewInvoice: "/app/accounting/invoices/view-invoice",


    systemSettings: "/app/system-settings",

    profileSettings: "/app/profile-settings",

    userAccount: "/app/user-management/accounts",
    addUserAccount: "/app/user-management/accounts/add-user",
    editUserAccount: "/app/user-management/accounts/edit-user",
    userRoles: "/app/user-management/roles",
    
    auditTrails: "/app/audit-trails",
    help: "/app/help",
    
  }

  export const eventTypes = [
    'keypress',
    'mousemove',
    'mousedown',
    'scroll',
    'touchmove',
    'pointermove',
  ];

  export const PAGE_SIZE = 10

  export const PER_PAGES = [
    10, 25, 50, 100
  ] as number[]


  export const GENDER_OPTIONS = [
    { value: "m", label: "Male" },
     { value: "f", label: "Female" }
  ]

  export const NOTIFICATION_OPTIONS = [
    { value: "sms", label: "SMS" },
     { value: "email", label: "Email" }
  ]

  export const YES_NO_OPTIONS = [
    { value: "true", label: "Yes" },
     { value: "false", label: "No" }
  ]

  export const ACTIVE_STATUS_OPTIONS = [
    { value: "active", label: "Active" },
     { value: "inactive", label: "Inactive" }
  ]

  export const DEDUCT_FROM_OPTIONS = [
    { value: "annual", label: "Annual" },
     { value: "sick", label: "Sick" }

  ]

  export const COUNTRY_LIST = [
  // { label: 'Afghanistan', value: 'AF' },
  // { label: 'Albania', value: 'AL' },
  // { label: 'Algeria', value: 'DZ' },
  // { label: 'Andorra', value: 'AD' },
  // { label: 'Angola', value: 'AO' },
  // { label: 'Antigua and Barbuda', value: 'AG' },
  // { label: 'Argentina', value: 'AR' },
  // { label: 'Armenia', value: 'AM' },
  // { label: 'Australia', value: 'AU' },
  // { label: 'Austria', value: 'AT' },
  // { label: 'Azerbaijan', value: 'AZ' },
  // { label: 'Bahamas', value: 'BS' },
  // { label: 'Bahrain', value: 'BH' },
  // { label: 'Bangladesh', value: 'BD' },
  // { label: 'Barbados', value: 'BB' },
  // { label: 'Belarus', value: 'BY' },
  // { label: 'Belgium', value: 'BE' },
  // { label: 'Belize', value: 'BZ' },
  // { label: 'Benin', value: 'BJ' },
  // { label: 'Bhutan', value: 'BT' },
  // { label: 'Bolivia', value: 'BO' },
  // { label: 'Bosnia and Herzegovina', value: 'BA' },
  // { label: 'Botswana', value: 'BW' },
  // { label: 'Brazil', value: 'BR' },
  // { label: 'Brunei', value: 'BN' },
  // { label: 'Bulgaria', value: 'BG' },
  // { label: 'Burkina Faso', value: 'BF' },
  // { label: 'Burundi', value: 'BI' },
  // { label: 'Cabo Verde', value: 'CV' },
  // { label: 'Cambodia', value: 'KH' },
  // { label: 'Cameroon', value: 'CM' },
  // { label: 'Canada', value: 'CA' },
  // { label: 'Central African Republic', value: 'CF' },
  // { label: 'Chad', value: 'TD' },
  // { label: 'Chile', value: 'CL' },
  // { label: 'China', value: 'CN' },
  // { label: 'Colombia', value: 'CO' },
  // { label: 'Comoros', value: 'KM' },
  // { label: 'Congo (Congo-Brazzaville)', value: 'CG' },
  // { label: 'Costa Rica', value: 'CR' },
  // { label: 'Croatia', value: 'HR' },
  // { label: 'Cuba', value: 'CU' },
  // { label: 'Cyprus', value: 'CY' },
  // { label: 'Czechia (Czech Republic)', value: 'CZ' },
  // { label: 'Democratic Republic of the Congo', value: 'CD' },
  // { label: 'Denmark', value: 'DK' },
  // { label: 'Djibouti', value: 'DJ' },
  // { label: 'Dominica', value: 'DM' },
  // { label: 'Dominican Republic', value: 'DO' },
  // { label: 'Ecuador', value: 'EC' },
  // { label: 'Egypt', value: 'EG' },
  // { label: 'El Salvador', value: 'SV' },
  // { label: 'Equatorial Guinea', value: 'GQ' },
  // { label: 'Eritrea', value: 'ER' },
  // { label: 'Estonia', value: 'EE' },
  // { label: 'Eswatini (fmr. "Swaziland")', value: 'SZ' },
  // { label: 'Ethiopia', value: 'ET' },
  // { label: 'Fiji', value: 'FJ' },
  // { label: 'Finland', value: 'FI' },
  // { label: 'France', value: 'FR' },
  // { label: 'Gabon', value: 'GA' },
  // { label: 'Gambia', value: 'GM' },
  // { label: 'Georgia', value: 'GE' },
  // { label: 'Germany', value: 'DE' },
  { label: 'Ghana', value: 'GH' },
  // { label: 'Greece', value: 'GR' },
  // { label: 'Grenada', value: 'GD' },
  // { label: 'Guatemala', value: 'GT' },
  // { label: 'Guinea', value: 'GN' },
  // { label: 'Guinea-Bissau', value: 'GW' },
  // { label: 'Guyana', value: 'GY' },
  // { label: 'Haiti', value: 'HT' },
  // { label: 'Honduras', value: 'HN' },
  // { label: 'Hungary', value: 'HU' },
  // { label: 'Iceland', value: 'IS' },
  // { label: 'India', value: 'IN' },
  // { label: 'Indonesia', value: 'ID' },
  // { label: 'Iran', value: 'IR' },
  // { label: 'Iraq', value: 'IQ' },
  // { label: 'Ireland', value: 'IE' },
  // { label: 'Israel', value: 'IL' },
  // { label: 'Italy', value: 'IT' },
  // { label: 'Jamaica', value: 'JM' },
  // { label: 'Japan', value: 'JP' },
  // { label: 'Jordan', value: 'JO' },
  // { label: 'Kazakhstan', value: 'KZ' },
  // { label: 'Kenya', value: 'KE' },
  // { label: 'Kiribati', value: 'KI' },
  // { label: 'Kuwait', value: 'KW' },
  // { label: 'Kyrgyzstan', value: 'KG' },
  // { label: 'Laos', value: 'LA' },
  // { label: 'Latvia', value: 'LV' },
  // { label: 'Lebanon', value: 'LB' },
  // { label: 'Lesotho', value: 'LS' },
  // { label: 'Liberia', value: 'LR' },
  // { label: 'Libya', value: 'LY' },
  // { label: 'Liechtenstein', value: 'LI' },
  // { label: 'Lithuania', value: 'LT' },
  // { label: 'Luxembourg', value: 'LU' },
  // { label: 'Madagascar', value: 'MG' },
  // { label: 'Malawi', value: 'MW' },
  // { label: 'Malaysia', value: 'MY' },
  // { label: 'Maldives', value: 'MV' },
  // { label: 'Mali', value: 'ML' },
  // { label: 'Malta', value: 'MT' },
  // { label: 'Marshall Islands', value: 'MH' },
  // { label: 'Mauritania', value: 'MR' },
  // { label: 'Mauritius', value: 'MU' },
  // { label: 'Mexico', value: 'MX' },
  // { label: 'Micronesia', value: 'FM' },
  // { label: 'Moldova', value: 'MD' },
  // { label: 'Monaco', value: 'MC' },
  // { label: 'Mongolia', value: 'MN' },
  // { label: 'Montenegro', value: 'ME' },
  // { label: 'Morocco', value: 'MA' },
  // { label: 'Mozambique', value: 'MZ' },
  // { label: 'Myanmar (formerly Burma)', value: 'MM' },
  // { label: 'Namibia', value: 'NA' },
  // { label: 'Nauru', value: 'NR' },
  // { label: 'Nepal', value: 'NP' },
  // { label: 'Netherlands', value: 'NL' },
  // { label: 'New Zealand', value: 'NZ' },
  // { label: 'Nicaragua', value: 'NI' },
  // { label: 'Niger', value: 'NE' },
  // { label: 'Nigeria', value: 'NG' },
  // { label: 'North Korea', value: 'KP' },
  // { label: 'North Macedonia', value: 'MK' },
  // { label: 'Norway', value: 'NO' },
  // { label: 'Oman', value: 'OM' },
  // { label: 'Pakistan', value: 'PK' },
  // { label: 'Palau', value: 'PW' },
  // { label: 'Palestine State', value: 'PS' },
  // { label: 'Panama', value: 'PA' },
  // { label: 'Papua New Guinea', value: 'PG' },
  // { label: 'Paraguay', value: 'PY' },
  // { label: 'Peru', value: 'PE' },
  // { label: 'Philippines', value: 'PH' },
  // { label: 'Poland', value: 'PL' },
  // { label: 'Portugal', value: 'PT' },
  // { label: 'Qatar', value: 'QA' },
  // { label: 'Romania', value: 'RO' },
  // { label: 'Russia', value: 'RU' },
  // { label: 'Rwanda', value: 'RW' },
  // { label: 'Saint Kitts and Nevis', value: 'KN' },
  // { label: 'Saint Lucia', value: 'LC' },
  // { label: 'Saint Vincent and the Grenadines', value: 'VC' },
  // { label: 'Samoa', value: 'WS' },
  // { label: 'San Marino', value: 'SM' },
  // { label: 'Sao Tome and Principe', value: 'ST' },
  // { label: 'Saudi Arabia', value: 'SA' },
  // { label: 'Senegal', value: 'SN' },
  // { label: 'Serbia', value: 'RS' },
  // { label: 'Seychelles', value: 'SC' },
  // { label: 'Sierra Leone', value: 'SL' },
  // { label: 'Singapore', value: 'SG' },
  // { label: 'Slovakia', value: 'SK' },
  // { label: 'Slovenia', value: 'SI' },
  // { label: 'Solomon Islands', value: 'SB' },
  // { label: 'Somalia', value: 'SO' },
  // { label: 'South Africa', value: 'ZA' },
  // { label: 'South Korea', value: 'KR' },
  // { label: 'South Sudan', value: 'SS' },
  // { label: 'Spain', value: 'ES' },
  // { label: 'Sri Lanka', value: 'LK' },
  // { label: 'Sudan', value: 'SD' },
  // { label: 'Suriname', value: 'SR' },
  // { label: 'Sweden', value: 'SE' },
  // { label: 'Switzerland', value: 'CH' },
  // { label: 'Syria', value: 'SY' },
  // { label: 'Taiwan', value: 'TW' },
  // { label: 'Tajikistan', value: 'TJ' },
  // { label: 'Tanzania', value: 'TZ' },
  // { label: 'Thailand', value: 'TH' },
  // { label: 'Timor-Leste', value: 'TL' },
  // { label: 'Togo', value: 'TG' },
  // { label: 'Tonga', value: 'TO' },
  // { label: 'Trinidad and Tobago', value: 'TT' },
  // { label: 'Tunisia', value: 'TN' },
  // { label: 'Turkey', value: 'TR' },
  // { label: 'Turkmenistan', value: 'TM' },
  // { label: 'Tuvalu', value: 'TV' },
  // { label: 'Uganda', value: 'UG' },
  // { label: 'Ukraine', value: 'UA' },
  // { label: 'United Arab Emirates', value: 'AE' },
  // { label: 'United Kingdom', value: 'GB' },
  // { label: 'United States of America', value: 'US' },
  // { label: 'Uruguay', value: 'UY' },
  // { label: 'Uzbekistan', value: 'UZ' },
  // { label: 'Vanuatu', value: 'VU' },
  // { label: 'Venezuela', value: 'VE' },
  // { label: 'Vietnam', value: 'VN' },
  // { label: 'Yemen', value: 'YE' },
  // { label: 'Zambia', value: 'ZM' },
  // { label: 'Zimbabwe', value: 'ZW' },
];

export const GhanaRegionsList = [
  { label: "Ahafo", value: "ahafo" },
  { label: "Ashanti", value: "ashanti" },
  { label: "Bono", value: "bono" },
  { label: "Bono East", value: "bono-east" },
  { label: "Central", value: "central" },
  { label: "Eastern", value: "eastern" },
  { label: "Greater Accra", value: "greater-accra" },
  { label: "North East", value: "north-east" },
  { label: "Northern", value: "northern" },
  { label: "Oti", value: "oti" },
  { label: "Savannah", value: "savannah" },
  { label: "Upper East", value: "upper-east" },
  { label: "Upper West", value: "upper-west" },
  { label: "Volta", value: "volta" },
  { label: "Western", value: "western" },
  { label: "Western North", value: "western-north" }
];

export const colorArray = ['#F97316', '#3B82F6', '#EF4444', '#22C55E', '#A855F7', '#EC4899'];

export const colorStatusArray = ["success", "info", "warning", "danger", "alt", "dark"]


export const CEDI = "GH₵"
