services:
    j0gks00s880g04sog8ck48w0-125700396596:
        image: 'j0gks00s880g04sog8ck48w0:c018794144a54f81da2d1584e8ffa32835b2e276'
        container_name: j0gks00s880g04sog8ck48w0-125700396596
        restart: unless-stopped
        expose:
            - '3000'
        networks:
            coolify:
                aliases:
                    - j0gks00s880g04sog8ck48w0-125700396596
        mem_limit: '0'
        memswap_limit: '0'
        mem_swappiness: 60
        mem_reservation: '0'
        cpus: 0.0
        cpu_shares: 1024
        env_file:
            - .env
        healthcheck:
            test:
                - CMD-SHELL
                - 'curl -s -X GET -f http://localhost:3000/ > /dev/null || wget -q -O- http://localhost:3000/ > /dev/null || exit 1'
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 5s
        labels:
            - traefik.enable=true
            - traefik.http.middlewares.gzip.compress=true
            - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
            - traefik.http.routers.http-0-j0gks00s880g04sog8ck48w0.entryPoints=http
            - traefik.http.routers.http-0-j0gks00s880g04sog8ck48w0.middlewares=redirect-to-https
            - 'traefik.http.routers.http-0-j0gks00s880g04sog8ck48w0.rule=Host(`mariseth.scaleforge.farm`) && PathPrefix(`/`)'
            - traefik.http.routers.http-0-j0gks00s880g04sog8ck48w0.service=http-0-j0gks00s880g04sog8ck48w0
            - traefik.http.routers.https-0-j0gks00s880g04sog8ck48w0.entryPoints=https
            - traefik.http.routers.https-0-j0gks00s880g04sog8ck48w0.middlewares=gzip
            - 'traefik.http.routers.https-0-j0gks00s880g04sog8ck48w0.rule=Host(`mariseth.scaleforge.farm`) && PathPrefix(`/`)'
            - traefik.http.routers.https-0-j0gks00s880g04sog8ck48w0.service=https-0-j0gks00s880g04sog8ck48w0
            - traefik.http.routers.https-0-j0gks00s880g04sog8ck48w0.tls.certresolver=letsencrypt
            - traefik.http.routers.https-0-j0gks00s880g04sog8ck48w0.tls=true
            - traefik.http.services.http-0-j0gks00s880g04sog8ck48w0.loadbalancer.server.port=3000
            - traefik.http.services.https-0-j0gks00s880g04sog8ck48w0.loadbalancer.server.port=3000
            - 'caddy_0.encode=zstd gzip'
            - 'caddy_0.handle_path.0_reverse_proxy={{upstreams 3000}}'
            - 'caddy_0.handle_path=/*'
            - caddy_0.header=-Server
            - 'caddy_0.try_files={path} /index.html /index.php'
            - 'caddy_0=https://mariseth.scaleforge.farm'
            - caddy_ingress_network=coolify
            - coolify.managed=true
            - coolify.version=4.0.0-beta.463
            - coolify.applicationId=4
            - coolify.type=application
            - coolify.name=j0gks00s880g04sog8ck48w0
            - coolify.resourceName=mariseth-frontend-production
            - coolify.projectName=mariseth-erp
            - coolify.serviceName=mariseth-frontend-production
            - coolify.environmentName=production
            - coolify.pullRequestId=0
networks:
    coolify:
        external: true
        name: coolify
        attachable: true
