import { useUserStore } from "@/app/providers/user-store-provider";


export interface IPermObj{
    codename: string;
    id: number;
    name: string;
  }

export type permType =
    | "accounting|download_invoice"
    | "accounting|download_waybill"
    | "accounting|list_expenses"
    | "accounting|list_invoices"
    | "accounting|list_waybills"
    | "accounting|view_invoice"
    | "accounting|view_waybill"
    | "account_management|create_admin"
    | "account_management|create_group_and_assign_roles"
    | "account_management|delete_admin"
    | "account_management|delete_groups_and_roles"
    | "account_management|list_admins"
    | "account_management|list_groups_and_roles"
    | "account_management|update_admin"
    | "account_management|update_groups_and_roles"
    | "audit_trail|list_inflow_history"
    | "audit_trail|list_outflow_history"
    | "credit|approve_deny_credit"
    | "credit|create_credit"
    | "credit|delete_credit"
    | "credit|list_credit_fulfill"
    | "credit|list_credits"
    | "credit|update_credit"
    | "credit|view_credit"
    | "credit|warehouse_manager_fulfill_credit"
    | "customer|create_customer"
    | "customer|delete_customer"
    | "customer|list_customers"
    | "customer|update_customer"
    | "customer|view_customer"
    | "employee|add_employee_disciplinary_action"
    | "employee|add_employee_qualification"
    | "employee|create_employee"
    | "employee|delete_employee"
    | "employee|list_employee_disciplinary_actions"
    | "employee|list_employees"
    | "employee|remove_employee_qualification"
    | "employee|update_employee"
    | "employee|view_employee"
    | "farm|create_farm"
    | "farm|delete_farm"
    | "farm|delete_farm_products"
    | "farm|list_farms"
    | "farm|update_farm"
    | "farm|view_farm"
    | "farmer|create_farmer"
    | "farmer|delete_farmer"
    | "farmer|get_farmer_credit_history"
    | "farmer|get_smallholders_by_lead"
    | "farmer|list_farmers"
    | "farmer|update_farmer"
    | "farmer|view_farmer"
    | "hr|create_department"
    | "hr|create_job_title"
    | "hr|delete_department"
    | "hr|delete_job_title"
    | "hr|list_departments"
    | "hr|list_job_titles"
    | "hr|update_department"
    | "hr|update_job_title"
    | "hr|view_department"
    | "hr|view_job_title"
    | "inflow_orders|approve_inflow_delivery_inspection"
    | "inflow_orders|approve_inflow_order"
    | "inflow_orders|create_inflow_order"
    | "inflow_orders|delete_inflow_order"
    | "inflow_orders|list_inflow_approvals"
    | "inflow_orders|list_inflow_orders"
    | "inflow_orders|update_inflow_order"
    | "inflow_orders|view_inflow_approval"
    | "inflow_orders|view_inflow_order"
    | "input_credit|create_input_credit"
    | "input_credit|create_input_credit_purchase"
    | "input_credit|delete_input_credit"
    | "input_credit|delete_input_credit_purchase"
    | "input_credit|list_input_credit"
    | "input_credit|list_input_credit_purchase"
    | "input_credit|update_input_credit"
    | "input_credit|view_input_credit"
    | "leave|approve_decline_leave_request"
    | "leave|create_leave_request"
    | "leave|create_leave_type"
    | "leave|delete_leave_request"
    | "leave|delete_leave_type"
    | "leave|list_leave_requests"
    | "leave|list_leave_types"
    | "leave|update_leave_request"
    | "leave|update_leave_type"
    | "leave|view_leave_request"
    | "leave|view_leave_type"
    | "outflow_approvals|list_outflow_approvals"
    | "outflow_approvals|mark_outflow_order_picked"
    | "outflow_approvals|verify_outflow_availability"
    | "outflow_approvals|view_outflow_approval"
    | "outflow_orders|assign_delivery_info"
    | "outflow_orders|create_outflow_order"
    | "outflow_orders|delete_outflow_order"
    | "outflow_orders|list_outflow_orders"
    | "outflow_orders|mark_outflow_complete"
    | "outflow_orders|mark_outflow_delivered"
    | "outflow_orders|record_outflow_payment"
    | "outflow_orders|update_outflow_order"
    | "outflow_orders|view_outflow_order"
    | "payback|create_payback"
    | "payback|list_paybacks"
    | "payback|update_payback"
    | "product|create_product"
    | "product|delete_product"
    | "product|get_product_movement"
    | "product|list_products"
    | "product|update_product"
    | "product|view_product"
    | "shared_app_settings|create_or_update_settings"
    | "shared_custom_types|create_custom_type"
    | "shared_custom_types|delete_custom_type"
    | "shared_custom_types|update_custom_type"
    | "training|add_training_attendee"
    | "training|create_training"
    | "training|delete_training"
    | "training|list_training_attendees"
    | "training|list_trainings"
    | "training|mark_training_attendee_present"
    | "training|remove_training_attendee"
    | "training|set_attendee_status"
    | "training|update_training"
    | "training|view_training"
    | "warehouse|add_remove_warehouse_manager"
    | "warehouse|create_warehouse"
    | "warehouse|delete_warehouse"
    | "warehouse|get_product_warehouse_movement"
    | "warehouse|get_warehouse_inventory"
    | "warehouse|list_warehouses"
    | "warehouse|update_warehouse"
    | "warehouse|upload_warehouses"
    | "warehouse|view_warehouse";


export function useHasAccess(hasPerm: permType){
    const userData = useUserStore((user) => user) as any;
    const permObj = userData?.user?.permissions
    return {
        loading: Object.keys(permObj || {}).length === 0,
        hasAccess: !!permObj?.[hasPerm],
    }
}