/**
 * Generated by @openapi-codegen
 *
 * @version v1
 */
export type ForgotPassword = {
  /**
   * @format email
   * @minLength 1
   */
  email: string;
};

export type UserWithToken = {
  id?: number;
  /**
   * @format email
   * @maxLength 254
   * @minLength 1
   */
  email: string;
  gender?: "m" | "f" | null;
  /**
   * @maxLength 30
   */
  first_name?: string;
  /**
   * @maxLength 30
   */
  last_name?: string;
  /**
   * @minLength 1
   */
  access_token?: string;
  /**
   * @minLength 1
   */
  refresh_token?: string;
  /**
   * @format uri
   */
  avatar?: string | null;
  user_type: "admin" | "user";
};

export type Login = {
  /**
   * @format email
   * @minLength 1
   */
  email: string;
  /**
   * @minLength 1
   */
  password: string;
};

export type Logout = {
  /**
   * @minLength 1
   */
  refresh_token: string;
};

export type Group = {
  id?: number;
  /**
   * @maxLength 150
   * @minLength 1
   */
  name: string;
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  rank?: number | null;
  permissions?: string;
  is_default?: string;
  description?: string | null;
};

export type User = {
  id?: number;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   *
   * @pattern ^[\w.@+-]+$
   * @maxLength 150
   * @minLength 1
   */
  username: string;
  /**
   * @maxLength 30
   */
  first_name?: string;
  /**
   * @maxLength 30
   */
  last_name?: string;
  /**
   * @format email
   * @maxLength 254
   * @minLength 1
   */
  email: string;
  gender?: "m" | "f" | null;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  is_verified?: boolean;
  /**
   * @format uri
   */
  avatar?: string | null;
  groups: Group[];
  organization?: string;
};

export type ResendVerificationCode = {
  /**
   * @format email
   * @minLength 1
   */
  email: string;
};

export type ResetPassword = {
  /**
   * @format email
   * @minLength 1
   */
  email: string;
  verification_code: number;
  /**
   * @minLength 1
   */
  new_password: string;
};

export type UpdateAccount = {
  id?: number;
  /**
   * @maxLength 30
   */
  first_name?: string;
  /**
   * @maxLength 30
   */
  last_name?: string;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  /**
   * @format uri
   */
  avatar?: string | null;
  gender?: "m" | "f" | null;
  /**
   * @format email
   * @maxLength 254
   * @minLength 1
   */
  email: string;
  user_type: "admin" | "user";
};

export type UpdatePassword = {
  /**
   * @minLength 1
   */
  old_password: string;
  /**
   * @minLength 1
   */
  new_password: string;
};

export type AccountVerification = {
  verification_code: number;
  /**
   * @format email
   * @minLength 1
   */
  email: string;
};

export type NewUser = {
  /**
   * @format email
   * @maxLength 254
   * @minLength 1
   */
  email: string;
  /**
   * @maxLength 30
   */
  first_name?: string;
  /**
   * Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
   *
   * @pattern ^[\w.@+-]+$
   * @maxLength 150
   * @minLength 1
   */
  username: string;
  /**
   * @maxLength 30
   */
  last_name?: string;
  gender?: "m" | "f" | null;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  /**
   * @format uri
   */
  avatar?: string;
  group: number;
  organization?: number;
  /**
   * @minLength 1
   */
  user_type?: string;
};

export type GroupWithRank = {
  id?: number;
  /**
   * @maxLength 150
   * @minLength 1
   */
  name: string;
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  rank?: number | null;
  /**
   * The permissions assigned to this group.
   *
   * @uniqueItems true
   */
  permissions?: number[];
  is_default?: string;
  description?: string | null;
};

export type Permission = {
  id?: number;
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  codename: string;
};

export type AppSetting = {
  id?: number;
  config?: Record<string, any> | null;
};

export type MobileResendVerificationCode = {
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
};

export type MobileLogin = {
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
  /**
   * @maxLength 4
   * @minLength 4
   */
  pin: string;
};

export type ShortRegion = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  /**
   * @maxLength 4
   * @minLength 1
   */
  code: string;
};

export type District = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
};

export type CustomType = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  name: string;
  /**
   * @maxLength 50
   * @minLength 1
   */
  category_name: string;
  /**
   * @maxLength 255
   */
  description?: string | null;
  /**
   * @maxLength 255
   */
  category_type?: string | null;
  is_default?: boolean;
};

export type ShortUser = {
  id?: number;
  /**
   * @format email
   * @maxLength 254
   * @minLength 1
   */
  email: string;
  /**
   * @maxLength 30
   */
  first_name?: string;
  /**
   * @maxLength 30
   */
  last_name?: string;
  gender?: "m" | "f" | null;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  user_type: "admin" | "user";
};

export type FullFarm = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  farm_id: string;
  farm_type: "internal" | "external";
  /**
   * @maxLength 50
   */
  type?: string | null;
  /**
   * @maxLength 100
   */
  name?: string | null;
  /**
   * @maxLength 255
   */
  location?: string | null;
  region: ShortRegion;
  district: District;
  /**
   * @maximum 2147483647
   * @minimum -2147483648
   */
  size: number;
  size_metric: CustomType;
  /**
   * @maxLength 255
   */
  livestock_kept?: string | null;
  has_access_to_market?: boolean;
  irrigation?: boolean | null;
  use_of_fertilizers?: Record<string, any> | null;
  farming_methods?: Record<string, any> | null;
  provide_training?: boolean;
  government_ngo_support?: boolean;
  /**
   * @maxLength 255
   */
  specify_support?: string | null;
  areas_of_assistance?: Record<string, any> | null;
  land_ownership: "owned" | "leased" | "communal" | "other";
  /**
   * @maxLength 255
   */
  other_specification?: string | null;
  created_by: ShortUser;
  /**
   * @format date-time
   */
  date_created?: string;
  crops?: string;
  livestock?: string;
  farmer?: string;
} | null;

export type FullFarmer = {
  id?: number;
  type: "lead" | "smallholder";
  /**
   * @maxLength 50
   * @minLength 1
   */
  farmer_id: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  first_name: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  last_name: string;
  /**
   * @maxLength 100
   */
  other_names?: string | null;
  gender: "m" | "f";
  /**
   * @format date
   */
  date_of_birth?: string | null;
  /**
   * @maxLength 50
   */
  id_number?: string | null;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  /**
   * @format email
   * @maxLength 254
   */
  email?: string | null;
  /**
   * @maxLength 255
   */
  address?: string | null;
  /**
   * @maxLength 100
   */
  village?: string | null;
  region: ShortRegion;
  district: District;
  /**
   * @maxLength 100
   */
  country?: string | null;
  farm?: FullFarm;
  lead_farmer?: string;
  leadership_experience?: Record<string, any> | null;
  support_assistance?: Record<string, any> | null;
  created_by: ShortUser;
  /**
   * @format date-time
   */
  date_created?: string;
  /**
   * @maxLength 50
   */
  id_type?: string | null;
  number_of_smallholders?: string;
  documents?: string;
};

export type MobileUserWithTokenAndFarmer = {
  id?: number;
  /**
   * @format email
   * @maxLength 254
   * @minLength 1
   */
  email: string;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  /**
   * @maxLength 30
   */
  first_name?: string;
  /**
   * @maxLength 30
   */
  last_name?: string;
  is_verified?: boolean;
  user_type: "admin" | "user";
  status?: "active" | "inactive";
  farmer?: FullFarmer;
  /**
   * @minLength 1
   */
  access_token?: string;
  /**
   * @minLength 1
   */
  refresh_token?: string;
};

export type MobileRegister = {
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
};

export type MobileResetPassword = {
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
  code: number;
  /**
   * @minLength 1
   */
  new_pin: string;
};

export type SetPin = {
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
  /**
   * @maxLength 4
   * @minLength 4
   */
  pin: string;
};

export type MobileUpdateAccount = {
  id?: number;
  /**
   * @maxLength 30
   */
  first_name?: string;
  /**
   * @maxLength 30
   */
  last_name?: string;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  /**
   * @format uri
   */
  avatar?: string | null;
  gender?: "m" | "f" | null;
  /**
   * @format email
   * @maxLength 254
   * @minLength 1
   */
  email: string;
};

export type MobileUpdatePin = {
  /**
   * @minLength 1
   */
  old_pin: string;
  /**
   * @minLength 1
   */
  new_pin: string;
};

export type MobileAccountVerification = {
  code: number;
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
};

export type MobileCreditPayback = {
  id?: number;
  /**
   * @minLength 1
   */
  credit_id?: string;
  /**
   * @minLength 1
   */
  credit_type?: string;
  /**
   * @format decimal
   */
  credit_amount?: string;
  /**
   * Select payment method - cash or crop exchange
   */
  payback_method?: "cash_payback" | "crop_exchange" | null;
  /**
   * Amount being paid back in GHe
   *
   * @format decimal
   */
  amount: string;
  /**
   * Outstanding amount before this payment
   *
   * @format decimal
   */
  outstanding_before: string;
  /**
   * Outstanding amount after this payment
   *
   * @format decimal
   */
  outstanding_after: string;
  /**
   * @minLength 1
   */
  product_name?: string;
  /**
   * Number of bags/units exchanged
   *
   * @maximum 2147483647
   * @minimum 0
   */
  quantity_bags?: number | null;
  /**
   * Additional notes about this payment
   */
  comments?: string | null;
  /**
   * @format date
   */
  date_paid?: string;
  status?: "paid" | "partial";
  /**
   * @format date-time
   */
  date_created?: string;
};

export type MobileActiveCredit = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  credit_id: string;
  /**
   * @minLength 1
   */
  input_credit_category?: string;
  /**
   * @minLength 1
   */
  input_credit?: string;
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  quantity: number;
  /**
   * @minLength 1
   */
  quantity_metric_name?: string;
  notes?: string | null;
  /**
   * @format decimal
   */
  credit_amount: string;
  /**
   * @format date
   */
  issue_date?: string | null;
  /**
   * @format date
   */
  due_date?: string | null;
  /**
   * @format decimal
   */
  interest_rate?: string | null;
  /**
   * @format decimal
   */
  outstanding_amount?: string | null;
  payment_status?: "paid" | "partial" | "overdue" | "active" | "inactive";
  approval_status?: "approved" | "denied" | "pending" | "fulfilled";
  days_overdue?: string;
  total_paid?: string;
  recent_paybacks?: MobileCreditPayback[];
  /**
   * @format date-time
   */
  date_created?: string;
};

export type MobileCredit = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  credit_id: string;
  /**
   * @minLength 1
   */
  input_credit_category?: string;
  /**
   * @minLength 1
   */
  input_credit?: string;
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  quantity: number;
  /**
   * @minLength 1
   */
  quantity_metric_name?: string;
  notes?: string | null;
  /**
   * @format decimal
   */
  credit_amount: string;
  /**
   * @format date
   */
  issue_date?: string | null;
  /**
   * @format date
   */
  due_date?: string | null;
  /**
   * @format decimal
   */
  interest_rate?: string | null;
  /**
   * @format decimal
   */
  outstanding_amount?: string | null;
  payment_status?: "paid" | "partial" | "overdue" | "active" | "inactive";
  approval_status?: "approved" | "denied" | "pending" | "fulfilled";
  days_overdue?: string;
  /**
   * @format date-time
   */
  date_created?: string;
};

export type ShortProduct = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  product_id: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  type: "crop" | "other";
  status?: "active" | "inactive";
  /**
   * @maxLength 100
   */
  color?: string | null;
};

export type FarmProduct = {
  id?: number;
  product: ShortProduct;
  is_main_product?: boolean;
};

export type FarmDetail = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  farm_id: string;
  farm_type: "internal" | "external";
  /**
   * @maxLength 50
   */
  type?: string | null;
  /**
   * @maxLength 100
   */
  name?: string | null;
  /**
   * @maxLength 255
   */
  location?: string | null;
  region?: number | null;
  district?: number | null;
  /**
   * @maximum 2147483647
   * @minimum -2147483648
   */
  size: number;
  size_metric?: number | null;
  /**
   * @maxLength 255
   */
  livestock_kept?: string | null;
  has_access_to_market?: boolean;
  irrigation?: boolean | null;
  use_of_fertilizers?: Record<string, any> | null;
  farming_methods?: Record<string, any> | null;
  provide_training?: boolean;
  government_ngo_support?: boolean;
  /**
   * @maxLength 255
   */
  specify_support?: string | null;
  areas_of_assistance?: Record<string, any> | null;
  land_ownership: "owned" | "leased" | "communal" | "other";
  /**
   * @maxLength 255
   */
  other_specification?: string | null;
  created_by?: number | null;
  /**
   * @format date-time
   */
  date_created?: string;
  products: FarmProduct[];
};

export type Farm = {
  id?: number;
  farm_type: "internal" | "external";
  /**
   * @maxLength 50
   */
  type?: string | null;
  /**
   * @maxLength 100
   */
  name?: string | null;
  /**
   * @maxLength 255
   */
  location?: string | null;
  region?: number;
  district?: number;
  /**
   * @maximum 2147483647
   * @minimum -2147483648
   */
  size: number;
  size_metric?: number | null;
  /**
   * @maxLength 255
   */
  livestock_kept?: string | null;
  has_access_to_market?: boolean;
  irrigation?: boolean | null;
  use_of_fertilizers?: Record<string, any> | null;
  farming_methods?: Record<string, any> | null;
  provide_training?: boolean;
  government_ngo_support?: boolean;
  /**
   * @maxLength 255
   */
  specify_support?: string | null;
  areas_of_assistance?: Record<string, any> | null;
  /**
   * @minLength 1
   */
  land_ownership?: string | null;
  /**
   * @maxLength 255
   */
  other_specification?: string | null;
  livestock?: number[] | null;
  crops?: number[] | null;
  farmer?: number | null;
};

export type Credit = {
  id?: number;
  farmer: number;
  input_credit_category: number;
  input_credit: number;
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  quantity: number;
  quantity_metric: number;
  notes?: string | null;
  self_application?: boolean;
};

export type ShortFarmer = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  first_name: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  last_name: string;
  type: "lead" | "smallholder";
};

export type FullInputCredit = {
  id?: number;
  /**
   * @maxLength 50
   */
  input_credit_id?: string | null;
  category: CustomType;
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  /**
   * @format decimal
   */
  price?: string | null;
  weight?: number | null;
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  quantity?: number | null;
  /**
   * @format date-time
   */
  date_created?: string;
  created_by: ShortUser;
};

export type FullCredit = {
  id?: number;
  /**
   * @minLength 1
   */
  credit_id?: string;
  farmer: ShortFarmer;
  input_credit: FullInputCredit;
  quantity?: number;
  quantity_metric: CustomType;
  /**
   * @format decimal
   */
  credit_amount?: string;
  /**
   * @format date
   */
  issue_date?: string | null;
  /**
   * @format date
   */
  due_date?: string | null;
  /**
   * @format decimal
   */
  interest_rate?: string | null;
  /**
   * @minLength 1
   */
  payment_status: string;
  approval_status?: "approved" | "denied" | "pending" | "fulfilled";
  /**
   * @minLength 1
   */
  notes?: string | null;
  created_by: ShortUser;
  /**
   * @format decimal
   */
  outstanding_amount?: string | null;
  /**
   * @minLength 1
   */
  denial_notes?: string | null;
  self_application?: boolean;
  logs?: string;
};

export type CreditWarehouseAllocation = {
  warehouse: number;
  quantity: number;
};

export type CreditApproval = {
  /**
   * Approval action to perform
   */
  action: "approve" | "deny";
  /**
   * Required when rejecting a credit application
   */
  denial_notes?: string;
  /**
   * @format decimal
   */
  credit_amount?: string | null;
  /**
   * @format decimal
   */
  interest_rate?: string | null;
  /**
   * @format date
   */
  issue_date?: string | null;
  /**
   * @format date
   */
  due_date?: string | null;
  notes?: string;
  warehouses?: CreditWarehouseAllocation[];
};

export type Customer = {
  id?: number;
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
  /**
   * @format email
   * @maxLength 254
   */
  email?: string | null;
  /**
   * @maxLength 255
   */
  location?: string | null;
  /**
   * @maxLength 255
   */
  company?: string | null;
  comments?: string | null;
  /**
   * @format date-time
   */
  date_created?: string;
};

export type FullCustomer = {
  id?: number;
  /**
   * @maxLength 20
   * @minLength 1
   */
  customer_id: string;
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  /**
   * @maxLength 20
   * @minLength 1
   */
  phone_number: string;
  /**
   * @format email
   * @maxLength 254
   */
  email?: string | null;
  /**
   * @maxLength 255
   */
  location?: string | null;
  /**
   * @maxLength 255
   */
  company?: string | null;
  comments?: string | null;
  /**
   * @format date-time
   */
  date_created?: string;
  created_by?: ShortUser;
};

export type Department = {
  id?: number;
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  description?: string | null;
  /**
   * @maxLength 255
   */
  department_id?: string | null;
  status?: "active" | "inactive";
};

export type EmergencyContact = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  /**
   * @maxLength 50
   * @minLength 1
   */
  relationship: string;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
};

export type Qualification = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  title: string;
  /**
   * @minLength 1
   */
  description: string;
  /**
   * @format uri
   */
  certificate?: string | null;
};

export type EmployeeContract = {
  id?: number;
  /**
   * @format date
   */
  start_date: string;
  /**
   * @maxLength 100
   */
  ssnit_number?: string | null;
  /**
   * @maxLength 100
   */
  bank_name?: string | null;
  /**
   * @maxLength 100
   */
  bank_branch?: string | null;
  /**
   * @maxLength 100
   */
  account_number?: string | null;
  job_title?: number | null;
  department?: number | null;
  employment_type: "full_time" | "contract" | "internship" | "part_time";
  work_type: "remote" | "hybrid" | "on_site";
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  annual_leave_days?: number;
  /**
   * @maximum 2147483647
   * @minimum 0
   */
  sick_leave_days?: number;
  leave_rollover?: boolean;
};

export type Employee = {
  id?: number;
  /**
   * @minLength 1
   */
  employee_id?: string;
  /**
   * @maxLength 50
   * @minLength 1
   */
  first_name: string;
  /**
   * @maxLength 50
   * @minLength 1
   */
  last_name: string;
  gender: "m" | "f";
  relationship_status?: "single" | "married" | "widowed" | null;
  /**
   * @format email
   * @maxLength 254
   */
  email?: string | null;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  /**
   * @format date
   */
  date_of_birth?: string | null;
  /**
   * @maxLength 50
   */
  bank_account_number?: string | null;
  status?: "active" | "inactive" | "suspended" | "dismissed";
  emergency_contacts?: EmergencyContact[];
  qualifications?: Qualification[];
  contract?: EmployeeContract;
  notification?: "email" | "sms";
  ghana_card_number?: string | null;
  profile_picture?: string;
};

export type Expense = {
  id?: number;
  /**
   * @format date-time
   */
  date_created?: string;
  description?: string | null;
  /**
   * @format decimal
   */
  amount?: string;
  order_type: "inflow" | "outflow";
  order_detail?: string;
};

export type FarmDelete = {};

export type FarmProductDelete = {
  /**
   * @maxItems 100
   * @minItems 1
   */
  farm_product_ids: number[];
};

export type FarmerDocument = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  title: string;
  description?: string | null;
  /**
   * @format uri
   */
  document?: string | null;
};

export type Farmer = {
  id?: number;
  type: "lead" | "smallholder";
  /**
   * @maxLength 100
   * @minLength 1
   */
  first_name: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  last_name: string;
  /**
   * @maxLength 100
   */
  other_names?: string | null;
  gender: "m" | "f";
  /**
   * @format date
   */
  date_of_birth?: string | null;
  /**
   * @maxLength 50
   */
  id_number?: string | null;
  /**
   * @maxLength 40
   * @minLength 11
   */
  phone_number?: string | null;
  /**
   * @format email
   * @maxLength 254
   */
  email?: string | null;
  /**
   * @maxLength 255
   */
  address?: string | null;
  /**
   * @maxLength 100
   */
  village?: string | null;
  region?: number | null;
  district?: number | null;
  /**
   * @maxLength 100
   */
  country?: string | null;
  farm?: number | null;
  lead_farmer?: number | null;
  leadership_experience?: Record<string, any> | null;
  support_assistance?: Record<string, any> | null;
  /**
   * @maxLength 50
   */
  id_type?: string | null;
  documents?: FarmerDocument[];
};

export type Product = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  category?: number | null;
  /**
   * @format decimal
   */
  weight?: string | null;
  weight_metric?: number | null;
  /**
   * @format decimal
   */
  quantity?: string | null;
  quantity_metric?: number | null;
  type: "crop" | "other";
  season_status?: "in" | "out" | null;
  status?: "active" | "inactive";
  /**
   * @format date
   */
  season_start?: string | null;
  /**
   * @format date
   */
  season_end?: string | null;
  description?: string | null;
  /**
   * @maxLength 100
   */
  breed?: string | null;
  /**
   * @maxLength 100
   */
  color?: string | null;
};

export type FullProduct = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  product_id: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  category: CustomType;
  /**
   * @format decimal
   */
  weight?: string | null;
  weight_metric: CustomType;
  /**
   * @format decimal
   */
  quantity?: string | null;
  quantity_metric: CustomType;
  type: "crop" | "other";
  season_status?: "in" | "out" | null;
  status?: "active" | "inactive";
  /**
   * @format date
   */
  season_start?: string | null;
  /**
   * @format date
   */
  season_end?: string | null;
  description?: string | null;
  /**
   * @maxLength 100
   */
  breed?: string | null;
  /**
   * @maxLength 100
   */
  color?: string | null;
  created_by: ShortUser;
  /**
   * @format date-time
   */
  date_created?: string;
  /**
   * @format date
   */
  last_updated?: string;
};

export type Help = {
  id?: number;
  /**
   * @maxLength 255
   * @minLength 1
   */
  title: string;
  /**
   * @minLength 1
   */
  description: string;
  /**
   * @format uri
   * @maxLength 200
   * @minLength 1
   */
  url: string;
};

export type FullHelp = {
  id?: number;
  /**
   * @maxLength 255
   * @minLength 1
   */
  title: string;
  /**
   * @minLength 1
   */
  description: string;
  /**
   * @format uri
   * @maxLength 200
   * @minLength 1
   */
  url: string;
  created_by: ShortUser;
  /**
   * @format date-time
   */
  date_created?: string;
};

export type InflowOrderProduct = {
  id?: number;
  order_id?: string;
  /**
   * @minLength 1
   */
  serial_number?: string;
  product: number;
  farm: number;
  /**
   * @format decimal
   */
  quantity: string;
  /**
   * @format decimal
   */
  unit_price: string;
  /**
   * @minLength 1
   */
  problematic_quantity?: string | null;
  /**
   * @minLength 1
   */
  reason?: string | null;
  /**
   * @minLength 1
   */
  comment?: string | null;
  /**
   * @format decimal
   */
  total_cost?: string;
  /**
   * @format decimal
   */
  total_weight?: string;
};

export type InflowOrder = {
  id?: number;
  aggregator?: number | null;
  procurement_officer?: number | null;
  /**
   * @format date
   */
  order_creation_date: string;
  destination_warehouse: number;
  /**
   * @format date
   */
  expected_delivery_date: string;
  status?: "delivery_inspection" | "order_approval" | "approved" | "cancelled";
  /**
   * @maximum 2147483647
   * @minimum -2147483648
   */
  total_bags?: number;
  additional_costs?: string;
  /**
   * @format decimal
   */
  additional_cost_amount?: string;
  comments?: string;
  products: InflowOrderProduct[];
  /**
   * @format decimal
   */
  total_weight?: string;
  /**
   * @format decimal
   */
  expected_amount?: string;
  /**
   * @format decimal
   */
  actual_amount?: string;
};

export type InflowOrderHistory = {
  event_type?: "status_change" | "comment" | "document_upload";
  created_by: ShortUser;
  /**
   * @minLength 1
   */
  notes?: string;
  /**
   * @minLength 1
   */
  old_value?: string;
  /**
   * @minLength 1
   */
  new_value?: string;
  /**
   * @minLength 1
   */
  field_name?: string;
  /**
   * @format date-time
   */
  date_created?: string;
};

export type FullInflowOrder = {
  id?: number;
  /**
   * @minLength 1
   */
  order_id?: string | null;
  aggregator: ShortUser;
  procurement_officer: ShortUser;
  /**
   * @format date
   */
  order_creation_date: string;
  destination_warehouse?: string;
  /**
   * @format date
   */
  expected_delivery_date: string;
  /**
   * @format date
   */
  actual_delivery_date?: string | null;
  status?: "delivery_inspection" | "order_approval" | "approved" | "cancelled";
  /**
   * @maximum 2147483647
   * @minimum -2147483648
   */
  total_bags?: number;
  additional_costs?: string;
  /**
   * @format decimal
   */
  total_products_cost?: string;
  /**
   * @format decimal
   */
  additional_cost_amount?: string;
  /**
   * @format decimal
   */
  total_cost?: string;
  comments?: string;
  products?: string;
  media_files?: string;
  history: InflowOrderHistory[];
  /**
   * @maxLength 50
   */
  waybill_id?: string | null;
  /**
   * @format decimal
   */
  total_weight?: string;
  /**
   * @format decimal
   */
  expected_amount?: string;
  /**
   * @format decimal
   */
  actual_amount?: string;
};

export type DeliveryInspectionApproval = {
  complaints?: {
    [key: string]: string | null;
  }[];
  notes?: string;
  images?: string[];
};

export type JobTitle = {
  id?: number;
  /**
   * @maxLength 255
   * @minLength 1
   */
  name: string;
  level?: number | null;
  department: number;
  /**
   * @format uri
   * @maxLength 200
   */
  job_description_url?: string | null;
  /**
   * @maxLength 255
   */
  job_title_id?: string | null;
  probation?: boolean;
};

export type LeaveRequest = {
  id?: number;
  employee: number;
  leave_type: number;
  /**
   * @format date
   */
  start_date: string;
  /**
   * @format date
   */
  end_date: string;
  /**
   * @minLength 1
   */
  reason: string;
  status?: "pending" | "approved" | "declined" | "canceled" | "completed";
};

export type LeaveType = {
  id?: number;
  /**
   * @maxLength 50
   * @minLength 1
   */
  name: string;
  description?: string;
  /**
   * Maximum allowed days per year (null = unlimited)
   *
   * @maximum 2147483647
   * @minimum 0
   */
  max_days?: number | null;
  /**
   * Whether this leave type deducts from employee's leave allowance
   */
  deducts_from_allowance?: boolean;
  deduct_from?: "annual" | "sick";
};

export type OutflowOrderProduct = {
  warehouse_id: number;
  product_id: number;
  /**
   * @maximum 2147483647
   * @minimum -2147483648
   */
  expected_quantity?: number;
  /**
   * @format decimal
   */
  price_per_unit: string;
  /**
   * @format decimal
   */
  total_weight?: string;
} | null;

export type OutflowOrder = {
  customer: number;
  procurement_officer: number | null;
  /**
   * @maxLength 255
   * @minLength 1
   */
  destination: string;
  /**
   * @format date
   */
  expected_delivery_date: string;
  products: OutflowOrderProduct[] | null;
  total_quantity?: number;
  /**
   * @format decimal
   */
  total_cost?: string;
  extra_comments?: string;
  additional_costs?: string;
  /**
   * @format decimal
   */
  additional_cost_amount?: string;
  /**
   * @format decimal
   */
  total_weight?: string;
  /**
   * @format decimal
   */
  expected_amount?: string;
  /**
   * @format decimal
   */
  actual_amount?: string;
};

export type OutflowOrderApproval = {
  id?: number;
  /**
   * @minLength 1
   */
  order_id?: string;
  customer: Customer;
  procurement_officer: ShortUser;
  /**
   * @minLength 1
   */
  destination?: string;
  /**
   * @format date
   */
  expected_delivery_date?: string;
  status?:
    | "pending"
    | "availability_check"
    | "truck_pickup"
    | "delivered"
    | "partial_payment"
    | "full_payment"
    | "complete"
    | "cancelled"
    | "approved";
  total_quantity: number;
  /**
   * @format decimal
   */
  total_cost: string;
  /**
   * @format decimal
   */
  total_weight: string;
  warehouses?: string;
};

export type CreditPayback = {
  id?: number;
  credit: number;
  /**
   * Select payment method - cash or crop exchange
   */
  payback_method?: "cash_payback" | "crop_exchange" | null;
  /**
   * Amount being paid back in GHe
   *
   * @format decimal
   */
  amount: string;
  product?: number | null;
  /**
   * Number of bags/units exchanged
   *
   * @maximum 2147483647
   * @minimum 0
   */
  quantity_bags?: number | null;
  /**
   * Additional notes about this payment
   */
  comments?: string | null;
  /**
   * @format date
   */
  date_paid?: string;
  status?: "paid" | "partial";
  payment_status: "full" | "partial";
};

export type ShortCredit = {
  id?: number;
  /**
   * @minLength 1
   */
  credit_id?: string;
  farmer: ShortFarmer;
  input_credit: FullInputCredit;
  quantity?: number;
  quantity_metric: CustomType;
  /**
   * @format decimal
   */
  credit_amount?: string;
  /**
   * @format date
   */
  issue_date?: string | null;
  /**
   * @format date
   */
  due_date?: string | null;
  /**
   * @format decimal
   */
  interest_rate?: string | null;
  /**
   * @minLength 1
   */
  payment_status: string;
  approval_status?: "approved" | "denied" | "pending" | "fulfilled";
  /**
   * @minLength 1
   */
  notes?: string | null;
};

export type FullPayback = {
  id?: number;
  credit?: ShortCredit;
  /**
   * @minLength 1
   */
  payback_method: string;
  /**
   * Amount being paid back in GHe
   *
   * @format decimal
   */
  amount?: string;
  /**
   * @format decimal
   */
  outstanding_before: string;
  /**
   * @format decimal
   */
  outstanding_after: string;
  product?: ShortProduct;
  /**
   * Number of bags/units exchanged
   */
  quantity_bags?: number | null;
  /**
   * Additional notes about this payment
   *
   * @minLength 1
   */
  comments?: string | null;
  /**
   * @format date
   */
  date_paid?: string;
  /**
   * @minLength 1
   */
  status: string;
  created_by?: ShortUser;
  /**
   * @format date-time
   */
  date_created?: string;
};

export type Region = {
  id?: number;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  /**
   * @maxLength 4
   * @minLength 1
   */
  code: string;
  districts?: District[];
};

export type Training = {
  id?: number;
  /**
   * @minLength 1
   */
  training_id?: string;
  /**
   * @maxLength 200
   * @minLength 1
   */
  title: string;
  description?: string | null;
  training_type: "internal" | "external";
  training_mode: "online" | "offline";
  /**
   * @format date-time
   */
  start_date: string;
  /**
   * @format date-time
   */
  end_date: string;
  /**
   * @maxLength 200
   */
  location?: string | null;
  /**
   * @format uri
   * @maxLength 200
   */
  material_url?: string | null;
  /**
   * @default false
   */
  all_employees?: boolean;
  selected_employees?: number[];
  departments?: number[];
};

export type WarehouseProduct = {
  product: number;
  /**
   * @format decimal
   */
  weight?: string;
  /**
   * @format decimal
   */
  quantity?: string;
};

export type Warehouse = {
  id?: number;
  /**
   * @minLength 1
   */
  warehouse_id?: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  region?: number | null;
  district?: number | null;
  /**
   * @maxLength 50
   * @minLength 1
   */
  capacity: string;
  /**
   * @uniqueItems true
   */
  managers?: number[];
  products?: WarehouseProduct[];
};

export type ProductWarehouse = {
  product: ShortProduct;
  /**
   * @format decimal
   */
  weight?: string;
  /**
   * @format decimal
   */
  quantity?: string;
};

export type FullWarehouse = {
  id?: number;
  /**
   * @maxLength 20
   * @minLength 1
   */
  warehouse_id: string;
  /**
   * @maxLength 100
   * @minLength 1
   */
  name: string;
  region: ShortRegion;
  district: District;
  /**
   * @maxLength 50
   * @minLength 1
   */
  capacity: string;
  managers: ShortUser[];
  /**
   * @format date-time
   */
  date_created?: string;
  /**
   * @format date-time
   */
  date_modified?: string;
  products: ProductWarehouse[];
};
