/**
 * Generated by @openapi-codegen
 *
 * @version v1
 */
import type * as Schemas from "./adminApiSchemas";

export type Customer = Schemas.Customer;

export type Employee = Schemas.Employee;

export type MobileResendVerificationCode = Schemas.MobileResendVerificationCode;

export type LeaveRequest = Schemas.LeaveRequest;

export type OutflowOrder = Schemas.OutflowOrder;

export type Logout = Schemas.Logout;

export type Training = Schemas.Training;

export type Help = Schemas.Help;

export type Warehouse = Schemas.Warehouse;

export type Product = Schemas.Product;

export type GroupWithRank = Schemas.GroupWithRank;

export type JobTitle = Schemas.JobTitle;

export type NewUser = Schemas.NewUser;

export type Farm = Schemas.Farm;

export type Credit = Schemas.Credit;

export type CustomType = Schemas.CustomType;

export type Department = Schemas.Department;

export type Farmer = Schemas.Farmer;

export type InflowOrder = Schemas.InflowOrder;

export type FullInputCredit = Schemas.FullInputCredit;

export type LeaveType = Schemas.LeaveType;

export type OutflowOrderApproval = Schemas.OutflowOrderApproval;

export type CreditPayback = Schemas.CreditPayback;
